CREATE TABLE T_REGISTRATION_REQUEST (
    RQ_ID_C VARCHAR(36) PRIMARY KEY,
    RQ_USERNAME_C VARCHAR(255) NOT NULL,
    RQ_EMAIL_C VARCHAR(255) NOT NULL,
    RQ_PASSWORD_C VARCHAR(255) NOT NULL,
    RQ_STATUS_C VARCHAR(20) DEFAULT 'PENDING',
    RQ_CREATEDATE_D DATETIME NOT NULL,
    RQ_UPDATEDATE_D DATETIME
);

UPDATE T_CONFIG SET CFG_VALUE_C = '32' WHERE CFG_ID_C = 'DB_VERSION';